[build]
builder = "nixpacks"
buildCommand = "cd server && npm install"

[build.nixpacksPlan.variables]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "cd server && node index.js"
restartPolicyType = "on_failure"
